// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"tkkt-auth/src/config"
	"tkkt-auth/src/db"
	"tkkt-auth/src/repo"
	"tkkt-auth/src/user/usrhndlr"
	"tkkt-auth/src/user/usrsvc"
)

// Injectors from wire.go:

func Wire() (*Server, error) {
	configConfig := config.ProvideConfig()
	sqlxDB := db.ProvideDB(configConfig)
	repoRepo := repo.ProvideRepo(sqlxDB)
	service := usrsvc.ProvideService(repoRepo)
	handler := usrhndlr.ProvideHandler(service)
	server := ProvideServer(configConfig, handler)
	return server, nil
}
